// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACqZx9i_h4Vz_Jkmw39136TE5n2hFgbg4',
    appId: '1:357370558903:web:c09cc45d51eb1b9a531032',
    messagingSenderId: '357370558903',
    projectId: 'hackrice-carbon-footprint',
    authDomain: 'hackrice-carbon-footprint.firebaseapp.com',
    storageBucket: 'hackrice-carbon-footprint.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQdzn7m1t3JItMBNHXThzOKxjW3cn8Kc',
    appId: '1:357370558903:android:5afc30effbc797ce531032',
    messagingSenderId: '357370558903',
    projectId: 'hackrice-carbon-footprint',
    storageBucket: 'hackrice-carbon-footprint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefTSpR50pKuXA0DYPZfHEllD6rNKNN5o',
    appId: '1:357370558903:ios:0ab36d76e276a28d531032',
    messagingSenderId: '357370558903',
    projectId: 'hackrice-carbon-footprint',
    storageBucket: 'hackrice-carbon-footprint.appspot.com',
    iosBundleId: 'com.example.carbonFootprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefTSpR50pKuXA0DYPZfHEllD6rNKNN5o',
    appId: '1:357370558903:ios:642bc287e9754c5a531032',
    messagingSenderId: '357370558903',
    projectId: 'hackrice-carbon-footprint',
    storageBucket: 'hackrice-carbon-footprint.appspot.com',
    iosBundleId: 'com.example.carbonFootprint.RunnerTests',
  );
}
